export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCTS_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCTS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
